# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_title', models.CharField(max_length=500)),
                ('album_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.ManyToManyField(to='music.Keyword')),
                ('playslist_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='RatingKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.ManyToManyField(to='music.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SongAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('song_id', models.ManyToManyField(to='music.Song')),
            ],
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('song_id', models.ManyToManyField(to='music.Song')),
            ],
        ),
        migrations.CreateModel(
            name='SongGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ManyToManyField(to='music.Genre')),
                ('song_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
        ),
        migrations.CreateModel(
            name='SongKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.ManyToManyField(to='music.Keyword')),
                ('song_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
        ),
        migrations.CreateModel(
            name='SongRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=5)),
                ('song_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=120)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Playlist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
        ),
        migrations.AddField(
            model_name='songrating',
            name='user_id',
            field=models.ManyToManyField(to='music.User'),
        ),
        migrations.AddField(
            model_name='ratingkeyword',
            name='rating_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.SongRating'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_id',
            field=models.ManyToManyField(to='music.Song'),
        ),
        migrations.AddField(
            model_name='artistkeyword',
            name='keyword_id',
            field=models.ManyToManyField(to='music.Keyword'),
        ),
        migrations.AddField(
            model_name='albumkeyword',
            name='keyword_id',
            field=models.ManyToManyField(to='music.Keyword'),
        ),
    ]
