# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='AlbumName',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='PlaylistName',
        ),
    ]
