# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(default='username', max_length=20, verbose_name='Username')),
                ('bio', models.TextField(default='', max_length=500, verbose_name='About')),
                ('location', models.CharField(default='NEP', max_length=9, verbose_name='Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
