# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
