# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='./songs/test.mp3', upload_to='./songs/'),
        ),
    ]
