# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_userprofiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
    ]
