# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(default='./myadmin/song/test.mp3', upload_to='./myadmin/song/'),
        ),
    ]
