# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170722_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='AlbumName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='PlaylistName',
            new_name='name',
        ),
    ]
