# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170722_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
