# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170720_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(default='./test.mp3', upload_to='./'),
        ),
    ]
