# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170720_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio',
        ),
    ]
