# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deteled date'),
        ),
    ]
