# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofiles',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
