# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofiles_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='deleted',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deteled date'),
        ),
    ]
